In [4]:
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('/content/drive/MyDrive/ch5. 소득예측/train_3oo.csv')

In [ ]:
df.columns

Index(['ID', 'Age', 'Gender', 'Education_Status', 'Employment_Status',
       'Working_Week (Yearly)', 'Industry_Status', 'Occupation_Status', 'Race',
       'Hispanic_Origin', 'Martial_Status', 'Household_Summary', 'Citizenship',
       'Birth_Country', 'Tax_Status', 'Gains', 'Losses', 'Dividends',
       'Income_Status', 'Income', 'check_us', 'Age_category', 'revenue',
       'profit'],
      dtype='object')

In [ ]:
# # age-category 5단위로 나눠보기
# def get_category(age):
#   age_range = ''
#   if age < 5 : age_range = '0'
#   elif age <10 : age_range = '1'
#   elif age <15 : age_range = '2'
#   elif age <20 : age_range = '3'
#   elif age <25 : age_range = '4'
#   elif age <30 : age_range = '5'
#   elif age <35 : age_range = '6'
#   elif age <40 : age_range = '7'
#   elif age <45 : age_range = '8'
#   elif age <50 : age_range = '9'
#   elif age <55 : age_range = '10'
#   elif age <60 : age_range = '11'
#   elif age <65 : age_range = '12'
#   elif age <70 : age_range = '13'
#   elif age <75 : age_range = '14'
#   elif age <80 : age_range = '15'
#   elif age <85 : age_range = '16'
#   else : age_range = '17'

#   return age_range

In [ ]:
# df['Age_Category'] = df['Age'].apply(lambda x : get_category(x))
# # 적용 df['Age'].apply(lambda x : get_category(x))

In [ ]:
# df['Age_Category']

# 추가적인 변수에 대한 전처리 및 가설 검증 EDA 해보기

- Age    
> 20~60 working year / 나머지    
연령대 + 성별

In [ ]:
# 20~60 경제활동 / 나머지
def active_age(age) :
  active_age = ''
  if age >= 20 and age <= 60  : active_age = 'active'
  else : active_age = 'inactive'
  return active_age

In [ ]:
df['Active_age'] = df['Age'].apply(lambda x : active_age(x))

In [ ]:
df['Active_age']

0        inactive
1          active
2          active
3          active
4          active
           ...
19995      active
19996      active
19997      active
19998    inactive
19999      active
Name: Active_age, Length: 20000, dtype: object

In [ ]:
def set_m_age(age) :
  set_gender_age = ''
  if age <10 :
    set_gender_age = '0M'
  elif age <20 : set_gender_age = '10M'
  elif age <30 : set_gender_age = '20M'
  elif age <40 : set_gender_age = '30M'
  elif age <50 : set_gender_age = '40M'
  elif age <60 : set_gender_age = '50M'
  elif age <70 : set_gender_age = '60M'
  elif age <80 : set_gender_age = '70M'
  elif age <90 : set_gender_age = '80M'
  else : set_gender_age = '90M'

  return set_gender_age

def set_f_age(age) :
  set_gender_age = ''
  if age < 10 : set_gender_age = '0F'
  elif age < 20 : set_gender_age = '10F'
  elif age < 30 : set_gender_age = '20F'
  elif age < 40 : set_gender_age = '30F'
  elif age < 50 : set_gender_age = '40F'
  elif age < 60 : set_gender_age = '50F'
  elif age < 70 : set_gender_age = '60F'
  elif age < 80 : set_gender_age = '70F'
  elif age < 90 : set_gender_age = '80F'
  else : set_gender_age = '90F'

  return set_gender_age

In [ ]:
df['Set_gender_age'] = df['Age'].copy()

In [ ]:
con1 = df['Gender'] == 'M'
df.loc[con1,'Set_gender_age'] = df.loc[con1,'Set_gender_age'].apply(lambda x : set_m_age(x))

In [ ]:
con2 = df['Gender'] == 'F'
df.loc[con2,'Set_gender_age'] = df.loc[con2,'Set_gender_age'].apply(lambda x : set_f_age(x))

In [ ]:
df['Set_gender_age'].unique()

array(['60M', '30M', '50F', '40M', '30F', '20F', '50M', '70F', '10M',
       '40F', '10F', '70M', '20M', '0M', '60F', '0F', '80F', '80M', '90F',
       '90M'], dtype=object)

- Education_Status    
> children / 학생 / 고등학교 졸업 / 대학생 / 석-박사

In [ ]:
# # 가장 단순하게 생각해서 ..!!
# con1 = df['Education_Status'] == 'Children'
# con2 = df['Education_Status'] == 'Kindergarten'
# con3 = df['Education_Status'] == 'Elementary (1-4)'
# con4 = df['Education_Status'] == 'Elementary (5-6)'
# con5 = df['Education_Status'] == 'Middle (7-8)'
# con6 = df['Education_Status'] == 'High Freshman'
# con7 = df['Education_Status'] == 'High Sophomore'
# con8 = df['Education_Status'] == 'High Junior'
# con9 = df['Education_Status'] == 'High Senior'
# con10 = df['Education_Status'] == 'High graduate'
# con11 = df['Education_Status'] == 'Associates degree (Vocational)'
# con12 = df['Education_Status'] == 'Associates degree (Academic)'
# con13 = df['Education_Status'] == 'College'
# con14 = df['Education_Status'] == 'Bachelors degree'
# con15 = df['Education_Status'] == 'Masters degree'
# con16 = df['Education_Status'] == 'Doctorate degree'
# con17 = df['Education_Status'] == 'Professional degree'

# df['Group_Education'] = df['Education_Status']
# df.loc[con1, 'Group_Education'] = 'Children'

In [ ]:
# 학력 순서대로 리스트 만들기
edu_list = ['Children', 'Kindergarten','Elementary (1-4)', 'Elementary (5-6)', 'Middle (7-8)',
            'High Freshman', 'High Sophomore', 'High Junior', 'High Senior', 'High graduate',
            'Associates degree (Vocational)', 'Associates degree (Academic)', 'College', 'Bachelors degree',
            'Masters degree','Doctorate degree', 'Professional degree']
# edu_list[:1]
# edu_list[1:9]
# edu_list[9:10]
# edu_list[10:]
df['Degree_ox'] = df['Education_Status'].copy()

# Student /
for i in range(len(edu_list)):
  if i <= 9 :
    df.loc[(df['Education_Status'] == edu_list[i]), 'Degree_ox'] = 'o'
  else :
    df.loc[(df['Education_Status'] == edu_list[i]), 'Degree_ox'] = 'x'

In [ ]:
df['Degree_ox'].unique()

array(['o', 'x'], dtype=object)

In [ ]:
# 학력 순서대로 리스트 만들기
edu_list = ['Children', 'Kindergarten','Elementary (1-4)', 'Elementary (5-6)', 'Middle (7-8)',
            'High Freshman', 'High Sophomore', 'High Junior', 'High Senior', 'High graduate',
            'Associates degree (Vocational)', 'Associates degree (Academic)', 'College', 'Bachelors degree',
            'Masters degree','Doctorate degree', 'Professional degree']
# edu_list[:1]
# edu_list[1:9]
# edu_list[9:10]
# edu_list[10:]
df['Group_Education'] = df['Education_Status'].copy()

# Child / Student / Graduate / Degree
for i in range(len(edu_list)):
  if i == 0 :
    df.loc[(df['Education_Status'] == edu_list[i]), 'Group_Education'] = 'Children'
  elif i <= 8 :
    df.loc[(df['Education_Status'] == edu_list[i]), 'Group_Education'] = 'Student'
  elif i == 9 :
    df.loc[(df['Education_Status'] == edu_list[i]), 'Group_Education'] = 'Graduate'
  else:
    df.loc[(df['Education_Status'] == edu_list[i]), 'Group_Education'] = 'Degree'

In [ ]:
df['Group_Education'].unique()

array(['Student', 'Degree', 'Graduate', 'Children'], dtype=object)

- Employment_Status
> 1) 파트타임/풀타임/나머지    
2) 5가지로 분류    
children or armed forces    
full time    
not working    
part-time    
seeking

In [ ]:
df['Employment_Status'].unique()

array(['Full-Time', 'Children or Armed Forces', 'Not Working',
       'Seeking Full-Time', 'Choice Part-Time',
       'Part-Time (Usually Part-Time)', 'Part-Time (Usually Full-Time)',
       'Seeking Part-Time'], dtype=object)

In [ ]:
# 1) 파트 / 풀 나머지m
emp_list = ['Children or Armed Forces', 'Full-Time', 'Not Working', 'Choice Part-Time',
           'Part-Time (Usually Part-Time)', 'Part-Time (Usually Full-Time)','Seeking Full-Time', 'Seeking Part-Time']


for i in range(len(emp_list)):
  if i == 0 :
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group1_Employment'] = 'other'
  elif i == 1 :
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group1_Employment'] = 'full_time'
  elif i == 2 :
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group1_Employment'] = 'other'
  elif 2 < i <= 5 :
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group1_Employment'] = 'part_time'
  elif i > 5:
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group1_Employment'] = 'other'

In [ ]:
df['Group1_Employment'].unique()

array(['full_time', 'other', 'part_time'], dtype=object)

In [ ]:
df.groupby('Group1_Employment')['Income'].count()

Group1_Employment
full_time     6588
other        12561
part_time      851
Name: Income, dtype: int64

In [ ]:
# 2) 5가지로 분류
emp_list = ['Children or Armed Forces', 'Full-Time', 'Not Working', 'Choice Part-Time',
           'Part-Time (Usually Part-Time)', 'Part-Time (Usually Full-Time)','Seeking Full-Time', 'Seeking Part-Time']

# emp_list[:1]
# emp_list[1:2]
# emp_list[2:3]
# emp_list[3:6]
emp_list[6:]

for i in range(len(emp_list)):
  if i == 0 :
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group2_Employment'] = 'children_or_armed_forces'
  elif i == 1 :
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group2_Employment'] = 'full_time'
  elif i == 2 :
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group2_Employment'] = 'not_working'
  elif 2 < i <= 5 :
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group2_Employment'] = 'part_time'
  elif i > 5:
    df.loc[(df['Employment_Status'] == emp_list[i]), 'Group2_Employment'] = 'seeking'

In [ ]:
df['Group2_Employment'].unique()

array(['full_time', 'children_or_armed_forces', 'not_working', 'seeking',
       'part_time'], dtype=object)

- Martial_Status
> Married / single / 나머지

In [ ]:
df['Martial_Status'].unique()

array(['Married', 'Separated', 'Divorced', 'Widowed', 'Single',
       'Married (Spouse Absent)', 'Married (Armed Force Spouse)'],
      dtype=object)

In [ ]:
emp_list = ['Married',  'Married (Spouse Absent)', 'Married (Armed Force Spouse)', 'Single', 'Separated', 'Divorced', 'Widowed', ]

# emp_list[:1]
# emp_list[1:2]
# emp_list[2:3]
# emp_list[3:6]
# emp_list[6:]

df['re_martial'] = df['Martial_Status'].copy()

# Child / Student / Graduate / Degree
for i in range(len(emp_list)):
  if i <= 2 :
    df.loc[(df['Martial_Status'] == emp_list[i]), 're_martial'] = 'Married'
  elif i == 3 :
    df.loc[(df['Martial_Status'] == emp_list[i]), 're_martial'] = 'Single'
  else:
    df.loc[(df['Martial_Status'] == emp_list[i]), 're_martial'] = 'the_other'

In [ ]:
df['re_martial'].unique()

array(['Married', 'the_other', 'Single'], dtype=object)

- Citizenship
> Native / Foreign

In [ ]:
# Citizenship -> Native인지 아닌지 구분
def native_ox(df) :
  con1 = df['Citizenship'] == 'Native'
  con2 = df['Citizenship'] == 'Native (Born in Puerto Rico or US Outlying)'
  con3 = df['Citizenship'] == 'Native (Born Abroad)'
  con4 = df['Citizenship'] == 'Foreign-born (Non-US Citizen)'
  con5 = df['Citizenship'] == 'Foreign-born (Naturalized US Citizen)'
  df.loc[con1 | con2 | con3,'Native_ox'] = 'Native'
  df.loc[con4 | con5,'Native_ox'] = 'Non-Native'

In [ ]:
native_ox(df)

In [ ]:
df['Native_ox'].unique()

array(['Native', 'Non-Native'], dtype=object)

- Hispanic Origin
> All other O / X

In [ ]:
# Hispanic -> All other인지 아닌지 구분
def allother_ox(df) :
  con0 = df['Hispanic_Origin'] == 'All other'
  con1 = df['Hispanic_Origin'] != 'All other'
  df.loc[con0,'Allother_ox'] = 'O'
  df.loc[con1,'Allother_ox'] = 'X'

In [ ]:
allother_ox(df)

- Race 백인  o / x

In [ ]:
# Race 인지 아닌
def Race_ox(df) :
  con0 = df['Race'] == 'White'
  con1 = df['Race'] != 'White'
  df.loc[con0,'Race_ox'] = 'O'
  df.loc[con1,'Race_ox'] = 'X'

In [ ]:
Race_ox(df)

- 이익과 손실 비율
> : gains / losses → 주식 투자 성과 고려

In [ ]:
# 데이터를 확인해본 결과 빼는 것이 좋을 것 같음.

- 데이터 저장

In [ ]:
df.to_csv('/content/drive/MyDrive/ch5. 소득예측/train_3xx.csv', index = False)